### ISSUE TITLE
Fix atom unable to install packages behind corporate proxy

### ISSUE THREAD

**Issue by genkio** [genkio/blog#28]
Thanks [TedThiCo](https://github.com/atom/apm/issues/322) for the solution.

Windows temporary:
`set ATOM_NODE_URL=http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist`

Windows permanently:
`setx ATOM_NODE_URL http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist /M`

Linux
`export ATOM_NODE_URL=http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist`

**Comment by diegozea** [comment]
This works! :D

```
diego@SIRRAH:~/.atom$ apm install language-julia
Installing language-julia to /home/diego/.atom/packages ✗
Request for package information failed: tunneling socket could not be established, cause=140190236563264:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:782:
 (5 attempts) (ECONNRESET)
diego@SIRRAH:~/.atom$ export ATOM_NODE_URL=http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist
diego@SIRRAH:~/.atom$ apm install language-julia
Installing language-julia to /home/diego/.atom/packages ✓
diego@SIRRAH:~/.atom$ cat .apmrc
proxy = http://my_host:my_port
strict-ssl = false
```

**Comment by peacekiller** [comment]
have still the same problem.
Thanks @j1wu for this workaround. it works! (using debian)

**Comment by ghost** [comment]
You can just set the proxy setting in apm:

```
apm config set proxy http://www.proxyurl.com:8080
apm config set https-proxy http://www.proxyurl.com:8080
```

**Comment by ashleylid** [comment]
@caesarivs THANK YOU! tried every other thing - this is the only thing that worked.
